---
- name: "Configure dns servers /etc/resolv.conf"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - resolv.conf

#- pause:
#    seconds: 15

#- name: "Remove resolvconf on Debian"
#  apt:
#    pkg: resolvconf
#    state: absent
#  when: ansible_os_family == 'Debian' and dns_remove_resolvconf
#
#- name: "Configured dhclient.conf"
#  lineinfile: >
#     regexp: "#?(supersede|prepend) {{ item.name }} "
#     line: "{{ dns_dhclient_rule }} {{ item.name }} {{ item.value }};"
#     dest: "{{ dns_dhclient_file }}"
#     state: present
#  with_items:
#    - { name: 'domain-name-servers', value: '{% for nameserver in dns_nameservers %}{{ nameserver }}{% if not loop.last %},{% endif %}{% endfor %}' }
#    - { name: 'domain-name', value: '\"{{dns_domain}}\"' }
#    - { name: 'domain-search', value: '{% for domainsearch in dns_searchs %}\"{{ domainsearch }}\"{% if not loop.last %}, {% endif %}{% endfor %}' }
#  when:  dns_forced_in_dhclientconf and item.value != ""
